### ISSUE TITLE
Vibrate only one time

### ISSUE THREAD

**Issue by ShuP1** [AsteroidOS/asteroid-alarmclock#6]
On ZenWatch 3 (swift),
Alarmclock vibrates only one short pulse.

With 8 august nightly image.

**Comment by FlorentRevest** [comment]
You/Your device's maintainer needs to convert the android's timed-output vibrator driver to a ffmemless driver. Similarly to what has been done here: https://github.com/AsteroidOS/meta-dory-hybris/blob/master/recipes-kernel/linux/linux-dory/0003-msm_pwm_vibrator-Convert-timed_output-APIs-to-ff_mem.patch and here: https://github.com/AsteroidOS/meta-bass-hybris/blob/master/recipes-kernel/linux/linux-bass/0004-msm_pwm_vibrator-Convert-timed_output-APIs-to-ff_mem.patch

The problem is not in asteroid-alarmclock. You should reopen an issue under meta-swift-hybris.

**Comment by violoncelloCH** [comment]
Is this the same for lg g watch r? My watch doesn't even vibrate one time... Also in Timer it doesn't vibrate...
